# 使用基类操作数据库. ps:基类包含自己个人比较喜欢的方法
from sql_factory import SqliteFactory

# Notice:
# this example need to you has know database and table.
# and the table structure:
#   | id  | int |
#   | name | string|

# Known to sqlite3 database file path
db_file_path = r"C:\Users\Administrator\AppData\Local\Temp\exa_db_name"
db_name = "exa_db_name"
table_name = "unittest_table"

db_factory = SqliteFactory()

# connection method 1:
db_factory.db(db_name=db_name, db_file=db_file_path)

# connection method 2 :
#        it's similar to create_engine syntax, but add first
#        argument db_name
#
# db_factory.connect(db_name, "sqlite:///" + db_file_path)

# remove file generated by sqlite3
# if os.path.isfile(self.db_temp_file):
#     os.remove(self.db_temp_file)

t = db_factory.db(db_name).table(table_name)

# t.remove() will remove all records
t.remove()

print("")
print("#### test insert and count ####")

# count the num of records
print("Before insert, record num: " + str(t.count()))
t.insert({"id": 1, "name": "unittest"})
print("After insert, record num: " + str(t.count()))

t.remove({"id": 1, "name": "unittest"})
print("After remove, record num: " + str(t.count()))

print("")
print("#### test get record ####")

t.insert({"id": 1, "name": "unittest"})
res = t.get({"id": 1})
id = res[0]['id']
name = res[0]['name']

print("insert record:  {'id': 1, 'name': 'unittest'}")
print("get record: " + str(res))
print("record id: " + str(id))
print("record name: " + name)

print("")
print("#### test update record ####")

t.update({"id": 1}, {"name": "update"})
res = t.get({"id": 1})
id = res[0]['id']
name = res[0]['name']

print("update record: ")
print("record id: " + str(id))
print("record name: " + name)
